import { String_Number, String_String } from './types';

export const API_FULLNAME: String_String = {
  AUD: 'Australian Dollar',
  BGN: 'Bulgarian Lev',
  BRL: 'Brazilian Real',
  CAD: 'Canadian Dollar',
  CHF: 'Swiss Franc',
  CNY: 'Chinese Renminbi Yuan',
  CZK: 'Czech Koruna',
  DKK: 'Danish Krone',
  EUR: 'Euro',
  GBP: 'British Pound',
  HKD: 'Hong Kong Dollar',
  HRK: 'Croatian Kuna',
  HUF: 'Hungarian Forint',
  IDR: 'Indonesian Rupiah',
  ILS: 'Israeli New Sheqel',
  INR: 'Indian Rupee',
  ISK: 'Icelandic Króna',
  JPY: 'Japanese Yen',
  KRW: 'South Korean Won',
  MXN: 'Mexican Peso',
  MYR: 'Malaysian Ringgit',
  NOK: 'Norwegian Krone',
  NZD: 'New Zealand Dollar',
  PHP: 'Philippine Peso',
  PLN: 'Polish Złoty',
  RON: 'Romanian Leu',
  RUB: 'Russian Ruble',
  SEK: 'Swedish Krona',
  SGD: 'Singapore Dollar',
  THB: 'Thai Baht',
  TRY: 'Turkish Lira',
  USD: 'United States Dollar',
  ZAR: 'South African Rand',
};
export const API_NAME_INDEX: String_Number = {
  AUD: 0,
  BGN: 1,
  BRL: 2,
  CAD: 3,
  CHF: 4,
  CNY: 5,
  CZK: 6,
  DKK: 7,
  EUR: 8,
  GBP: 9,
  HKD: 10,
  HRK: 11,
  HUF: 12,
  IDR: 13,
  ILS: 14,
  INR: 15,
  ISK: 16,
  JPY: 17,
  KRW: 18,
  MXN: 19,
  MYR: 20,
  NOK: 21,
  NZD: 22,
  PHP: 23,
  PLN: 24,
  RON: 25,
  RUB: 26,
  SEK: 27,
  SGD: 28,
  THB: 29,
  TRY: 30,
  USD: 31,
  ZAR: 32,
};
export const API_INDEX_NAME = [
  'AUD',
  'BGN',
  'BRL',
  'CAD',
  'CHF',
  'CNY',
  'CZK',
  'DKK',
  'EUR',
  'GBP',
  'HKD',
  'HRK',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'ISK',
  'JPY',
  'KRW',
  'MXN',
  'MYR',
  'NOK',
  'NZD',
  'PHP',
  'PLN',
  'RON',
  'RUB',
  'SEK',
  'SGD',
  'THB',
  'TRY',
  'USD',
  'ZAR',
];
